### ISSUE TITLE
This project seems dead

### ISSUE THREAD

**Issue by bmuller** [countergram/pytidylib#15]
Before I fork and create a new project - I just wanted to check and see if you still want to maintain this project.  HTML5 support is a must for a project I'm working on.  The last commit was over a year ago - and no release `0.3.0` was made to at least allow folks to specify a `LIB_NAMES` list for use w/ libtidy 5.

Thanks!

**Comment by countergram** [comment]
@bmuller been pretty short of time for a while, but I can get 0.3.0 up on PyPI (oversight on my part) and take another look at PRs

**Comment by bmuller** [comment]
OK - I'll hold off then.  If you're too busy and would like to hand off, I'd be happy to take over, so just let me know.

Really appreciate the hard work on making this project and open sourcing it!
