### ISSUE TITLE
uses old tidylib when newer is installed

### ISSUE THREAD

**Issue by unhammer** [countergram/pytidylib#8]
This happens on a Mac where the system has some old version of tidy (yes, there are even older ones), but the new version is installed from macports:

    $ locate tidy.h
    /Developer/SDKs/MacOSX10.5.sdk/usr/include/tidy/tidy.h
    /Developer/SDKs/MacOSX10.6.sdk/usr/include/tidy/tidy.h
    /opt/local/include/tidy.h
    /usr/include/tidy/tidy.h

The /opt one is the newest version, but tidylib seems to use the /usr/ one, since it gives bad output on certain html files, but good output if I prepend `/opt/local/lib/libtidy.dylib` to LIB_NAMES in __init__.py

**Comment by countergram** [comment]
Would you try the newest GitHub version? I refactored to allow configuration of the library to use (also prepping for tidy5)

**Comment by unhammer** [comment]
>>> import tidylib
    >>> import ctypes.util
    >>> tidylib.Tidy(lib_names=ctypes.util.find_library('tidy'))._tidy
    <CDLL '/opt/local/lib/libtidy.dylib', handle 100377730 at 10121b2d0>
    >>> 

Works for me :)
