### ISSUE TITLE
Support tidy5

### ISSUE THREAD

**Issue by countergram** [countergram/pytidylib#9]
The fork of tidy at https://github.com/htacg/tidy-html5 is (probably) going to be the mainline tidy going forward. pytidylib mostly functions with it already (albeit the library-name issue needs to be solved) but there are some differences in entity handling that cause tests to fail, and who knows what else.

**Comment by GertBurger** [comment]
+1

**Comment by davidryanorg** [comment]
+1

**Comment by countergram** [comment]
This will be addressed by allowing configuration of the tidy library name to use on instantiation. In git now and going for 0.3.0 soon.

**Comment by GertBurger** [comment]
So tidy5 is now in the debian and ubuntu repos via the tidy package. It pulls in libtidy5 which has the following libs:
/usr/lib/libtidy.so.5.2.0
/usr/lib/libtidy.so.5 -> libtidy.so.5.2.0

Notably they do not link it to libtidy.so

Should libtidy.so.5 then not be first in the list of LIB_NAMES?

**Comment by countergram** [comment]
This should be addressed now
